---
# Power Plug for Monitor
# Manufacturer: Refoss P11
# readme docs/Refoss_P11.md

substitutions:
  environment: p #Production
  system_name: plg02
  friendly_name: "Plug Monitor"
  device_description: "Power Plug Montior. Readme https://github.com/ghimele/esphome-config/blob/main/docs/Refoss_P11.md"
  ip_address: !secret EPP-PLG02_IP_ADDRESS
  project_name: "MAM.ESPHome Power Monitor Plug"
  version: 1.0.0
  status_led_pin: GPIO4
  update_interval: 10s


packages:
  device: !include devices/Refoss_P11_PMP.yaml
  