---
# Dimmer BedRoom 1
# Manufacturer: MOES
# readme docs/Moes_MS-105.md

substitutions:
  environment: p  # Production
  system_name: dmr01
  friendly_name: "Light BedRoom 01"
  device_description: "MOES Dimmer. Readme https://github.com/ghimele/esphome-config/blob/main/docs/Moes_MS-105.md"
  ip_address: !secret EPP-DMR01_IP_ADDRESS
  project_name: "MAM.ESPHome Dimmer Light"
  version: 1.0.0
  update_interval: 10s

packages:
  device: !include devices/MOES_MS-105.yaml
