---
# Crono
# Crono Thermostat.
# TODO readme crono.md
#

substitutions:
  environment: p  # Production
  system_name: crn01
  friendly_name: Crono Test
  device_description: "Crono thermostat device. Readme via TODO"
  ip_address: !secret EPP-CRN01_IP_ADDRESS
  project_name: "MAM.ESPHome Crono Thermostat"
  version: 1.0.0
  status_led_pin: GPIO02
  display_clk_pin: GPIO5
  display_mosi_pin: GPIO3
  display_cs_pin: GPIO6
  display_dc_pin: GPIO7
  display_busy_pin: GPIO4
  display_reset_pin: GPIO1
  target_temp_home: "21.5"
  target_temp_away: "17"
  target_temp_comfort: "22"
  target_temp_eco: "19.5"
  dht_pin: GPIO10
  dht_model: DHT22
  dht_temperature_id: "${system_name}_temperature"
  dht_temperature_name: "${friendly_name} Temperature"
  dht_temperature_icon: "mdi:thermometer"
  dht_humidity_id: "${system_name}_humidity"
  dht_humidity_name: "${friendly_name} Humidity"
  dht_humidity_icon: "mdi:water-percent"

packages:
  device: !include devices/ESPC3_Relay_X1.yaml
  debug: !include ./components/debug/debug_info.yaml
  display: !include ./components/displays/waveshare_epaper_4.20in.yaml
  sensor: !include ./components/sensors/dht.yaml

sensor:

  - platform: homeassistant
    name: "External Temperature"
    entity_id: sensor.daikin_soggiorno_outside_temperature
    id: outside_temperature

  - platform: homeassistant
    name: "Home Temperature"
    entity_id: sensor.crono_home_temperature
    id: home_temperature

switch:
  - platform: gpio
    id: heater_relay
    pin: 19
    name: "Relay Heater"
    restore_mode: ALWAYS_OFF

climate:
  - platform: thermostat
    name: "Thermostat"
    id: crono_thermostat
    sensor: home_temperature
    min_heating_off_time: 120s
    min_heating_run_time: 120s
    min_idle_time: 30s
    visual:
      min_temperature: 10
      max_temperature: 30
      temperature_step: 0.5
    heat_action:
      - switch.turn_on: heater_relay
    idle_action:
      - switch.turn_off: heater_relay
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: $target_temp_home
        mode: HEAT
      - name: Away
        default_target_temperature_low: $target_temp_away
        mode: HEAT
      - name: Comfort
        default_target_temperature_low: $target_temp_comfort
        mode: HEAT
      - name: Eco
        default_target_temperature_low: $target_temp_eco
        mode: HEAT
  
  # heat_mode:
  #   then:
  #     - script.execute: update_screen
  # off_mode:
  #   then:
  #     - script.execute: update_screen

font: !include ./components/fonts/climate_fonts.yaml

display:
  - id: !extend eink_display
    lambda: |-
      it.print(10, 10, id(wifi_font_20), TextAlign::CENTER, "Ciao Ciao");
