# Crono
#
# Crono Thermostat.
#
# TODO readme crono.md
#

substitutions:
  environment: p # Production
  system_name: crn01
  friendly_name: Crono Test
  device_description: "Crono thermostat device. Readme via TODO"
  ip_address: 192.168.51.20
  project_name: "MAM.ESPHome Crono Thermostat"
  version: 1.0.0
  display_clk_pin: GPIO5
  display_mosi_pin: GPIO3
  display_cs_pin: GPIO6
  display_dc_pin: GPIO7
  display_busy_pin: GPIO4
  display_reset_pin: GPIO2

packages:
  device: !include devices/ESPC3_Relay_X1.yaml
  debug: !include ./components/debug/debug_info.yaml
  display: !include ./components/displays/waveshare_epaper_4.20in.yaml

# https://esphome.io/components/esp32_ble_tracker.html?highlight=esp32_ble_tracker
# esp32_ble_tracker: 

sensor:
  - platform: homeassistant
    name: "External Temperature"
    entity_id: sensor.daikin_soggiorno_outside_temperature
    id: outside_temperature  
    
  - platform: homeassistant
    name: "Home Temperature"
    entity_id: sensor.crono_home_temperature
    id: home_temperature

switch: 
  - platform: gpio
    id: heater_relay
    pin: 19
    name: "Relay Heater"
    restore_mode: ALWAYS_OFF

climate:
  - platform: thermostat
    name: "Thermostat"
    id: crono_thermostat
    sensor: home_temperature
    min_heating_off_time: 120s
    min_heating_run_time: 120s
    min_idle_time: 30s
    visual:
      min_temperature: 10
      max_temperature: 30
      temperature_step: 0.5
    heat_action:
      - switch.turn_on: heater_relay
    idle_action:
      - switch.turn_off: heater_relay
    default_preset: Home
    preset:
      - name: Home
        default_target_temperature_low: 21
        mode: HEAT
      - name: Away
        default_target_temperature_low: 17
        mode: HEAT
      - name: Comfort
        default_target_temperature_low: 22
        mode: HEAT
      - name: Eco
        default_target_temperature_low: 19.5
        mode: HEAT
    # heat_mode: 
    #   then:
    #     - script.execute: update_screen
    # off_mode: 
    #   then:
    #     - script.execute: update_screen

font: !include ./components/fonts/climate_fonts.yaml

display: 
- id: !extend eink_display
  lambda: |-
    it.print(10, 10, id(wifi_font_20), TextAlign::CENTER, "Ciao Ciao");