---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
substitutions:
  ota_password: !secret OTA_PASSWORD

ota:
  - platform: esphome
    id: component_ota
    password: "${ota_password}"
  # - platform: http_request
    # safe_mode: true
    # reboot_timeout: 10min
    # num_attempts: 5
