---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
substitutions:
  wifi_ssid: !secret WIFI_SSID
  wifi_password: !secret WIFI_PASSWORD
  wifi_ap_password: !secret WIFI_AP_PASSWORD

wifi:
  id: component_wifi
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"
  reboot_timeout: 10min
  domain: .home.arpa
  use_address: "${ip_address}"
  ap:
    ssid: "${friendly_name} AP"
    password: "${wifi_ap_password}"
  # manual_ip:
  #   # Set this to the IP of the ESP
  # static_ip: "${ip_address}"
  #   # Set this to the IP address of the router. Often ends with .1
  # gateway: 192.168.51.1
  #   # The subnet of the network. 255.255.255.0 works for most home networks.
  # subnet: 255.255.255.0

sensor:
  - <<: !include ../sensors/wifi_signal_percentage.yaml
  - <<: !include ../sensors/wifi_signal.yaml
    on_value:
      - component.update: sensor_wifi_signal_percentage

text_sensor:
  - <<: !include ../text_sensors/wifi_info.yaml
