---
name: ESPHome CI

on:
  push:
    paths-ignore:
      - '**/README.md'
      - 'assets/**'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**/README.md'
      - 'assets/**'
      - 'docs/**'

jobs:
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v4.1.3
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1.5.0

  esphome:
    runs-on: ubuntu-latest
    needs: [yamllint]
    steps:
      - name: ⤵️ Check out configuration from GitHub
        uses: actions/checkout@v4.1.3
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9.15
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install "pillow==10.2.0"
          pip install esphome
          pip list
          esphome version
      - name: Copy secrets stub into secrets
        run: cp .github/secrets.fake.yaml ./secrets.yaml
      - name: Run esphome on all files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./ -type f -name "epp-*.yaml" -maxdepth 1); do esphome config "${file}"; done
