---
# DEBUG INFORMATION
# to be used as package
# Example
#
# packages:
#  debug: !include ./components/debug/debug_info.yaml
#
# End of Example

debug:
  update_interval: 300s

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
